---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - network.suslian.engineer
  resources:
  - unifinetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.suslian.engineer
  resources:
  - unifinetworks/finalizers
  verbs:
  - update
- apiGroups:
  - network.suslian.engineer
  resources:
  - unifinetworks/status
  verbs:
  - get
  - patch
  - update
