# permissions for end users to view unifinetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: unifinetwork-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: network-operator
    app.kubernetes.io/part-of: network-operator
    app.kubernetes.io/managed-by: kustomize
  name: unifinetwork-viewer-role
rules:
- apiGroups:
  - network.suslian.engineer
  resources:
  - unifinetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.suslian.engineer
  resources:
  - unifinetworks/status
  verbs:
  - get
